package vn.edu.hcmus.crypto.client;
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Main {
    
    public static void main(final String[] args) {
        System.out.println("");
    }
}
